function [logL] = loglikelihood1(theta, measurements, net)
%% This is the logarithm of the Gaussian Likelihood function
% 
% Usage:
% logL = loglikelihood1(theta, net)
%
% Inputs:
% theta:        The N x dim matrix of sample inputs;
% measurements: The 1 x 6 vector of measurements;
% net:          The trained ANN model function;
%
% Output:
% logL:         The N x 1 vector of loglikelihood values;
%
%% Function description:
model_output = (net(theta(:,1:2)'))'; % N x 6 vector

logL = zeros(size(theta,1),1); % N x 6 vector
for i = 1:size(theta,1)
logL(i) = - 0.5 .* (1./theta(i,3)).^2 .*(measurements(:,1) - model_output(i,1)).^2 -...
          length(measurements).*log(sqrt(2*pi).*theta(i,3)) +...
          - 0.5 .* (1./theta(i,4)).^2 .*(measurements(:,2) - model_output(i,2)).^2 -...
          length(measurements).*log(sqrt(2*pi).*theta(i,4)) +...
          - 0.5 .* (1./theta(i,5)).^2 .*(measurements(:,3) - model_output(i,3)).^2 -...
          length(measurements).*log(sqrt(2*pi).*theta(i,5)) +...
          - 0.5 .* (1./theta(i,6)).^2 .*(measurements(:,4) - model_output(i,4)).^2 -...
          length(measurements).*log(sqrt(2*pi).*theta(i,6)) +...
          - 0.5 .* (1./theta(i,7)).^2 .*(measurements(:,5) - model_output(i,5)).^2 -...
          length(measurements).*log(sqrt(2*pi).*theta(i,7)) +...
          - 0.5 .* (1./theta(i,8)).^2 .*(measurements(:,6) - model_output(i,6)).^2 -...
          length(measurements).*log(sqrt(2*pi).*theta(i,8));
end
end

